### ISSUE TITLE
Allow user to delete stored games

### ISSUE THREAD

**Issue by Beamanator** [Beamanator/Ulti-Mate#10]
There's a list item for this in my_games_list_long_press_menu, but it has not been implemented.

**Comment by navingator** [comment]
Funny that you mention this. I was running into the same issue today, and noticed that I had already written a number of functions for it in `MyGamesListFragment`. I need to investigate why this is not working.

**Comment by Beamanator** [comment]
Are you sure this is closed?

EDIT: Yep, it's closed. I just got the updated code and deleting works.
