### ISSUE TITLE
Improve Hard/Soft Cap Input handling

### ISSUE THREAD

**Issue by navingator** [Beamanator/Ulti-Mate#11]
Store soft/hard cap as date + time
Add validation for hard/soft cap - should be past current time

**Comment by Beamanator** [comment]
Added a default 75 minutes to current time for soft cap, 90 minutes for hard cap

Note: not going to store date as part of soft / hard cap yet
Kidding - now we're storing current year & day as part of date

Still need:
- [x] Validation for cap being past current time
- [x] Dealing with overnight soft / hard caps [night tournaments]

**Comment by Beamanator** [comment]
Completed soft cap code - need to modularize & add to hard cap

Overnight details: If cap is set in the past, automatically pretend like it's set for the next day. Snackbar pops up telling user how far into the future the cap is set for, and gives user a chance to undo that cap.
