### ISSUE TITLE
Add functionality to display more than 10 games in My Games Activity

### ISSUE THREAD

**Issue by navingator** [Beamanator/Ulti-Mate#14]
Currently, we only allow the user to see the last 10 games
`games = gameDbAdapter.getRecentGames(10,0);`

We should determine a strategy to allow users to see more games, perhaps temporarily arbitrarily increasing the limit to 20, 100, etc.

**Comment by Beamanator** [comment]
When the user scrolls down, app checks if 1) scrolling has stopped, and 2) last viewed game is max games in the adapter. if yes, loads up to 10 more.

Still need to do:
- [x] Prevent app from increasing gamesToLoad by 10 indefinitely
- [x] Go back to 10 games to load after moving away from the fragment MyGamesListFragment
