### ISSUE TITLE
Start Game Button Does Not Update After Updating Game Settings

### ISSUE THREAD

**Issue by navingator** [Beamanator/Ulti-Mate#21]
If the user 
1. Starts or resumes a game
2. Modifies the game Settings

The Start/Resume/End game button will read Start game instead of resume game.

**Comment by Beamanator** [comment]
Adding a new enum value to DisplayToLaunch - "UPDATE"

This will work exactly the same as the "RESUME" DisplayToLaunch.

**Comment by navingator** [comment]
Now, if I create a new game, the button displays "Resume Game" instead of "Start Game"
Reopening for further investigation - the code looks good at a cursory glance, but I'm sure we glossed over something.

EDIT: On a similar note, the top menu icons are also hidden - we should remember to update the menu when adding new enum values. Went ahead and fixed that one.

**Comment by Beamanator** [comment]
Some of the logic I had used for the "UPDATE" display needed to be changed after your template updates. We're good on that front now.
