### ISSUE TITLE
Add trigger points to notify the user of halftime

### ISSUE THREAD

**Issue by navingator** [Beamanator/Ulti-Mate#53]
In particular,
- [x] Halftime
- [x] ~~Soft Cap~~
- [x] ~~Hard Cap~~

May be worth attaching a notification for each. 

Splitting off time caps to issues #57 and #58

**Comment by Beamanator** [comment]
If notifications aren't implemented by Beta Release, remove Status Bar from GameDisplayActivity

**Comment by navingator** [comment]
Realistically, we'll need to add means to update statuses for all of the statuses
- [x] Not Started
- [x] Paused
- [x] First Half
- [x] Halftime
- [x] Second Half
- [x] ~~Soft Cap~~
- [x] ~~Hard Cap~~
- [x] Game Over
- [x] In Progress

Perhaps provide a listener that waits for status changes and performs actions based on them?

**Comment by navingator** [comment]
Logic for calculating halftime:

If the score is less than 2, we're not using halftime - set the game status to in progress.

Halftime score is half of the winning score, rounded up.
Get the winning score - if the score is less than the halftime score, then we're in the first half
If the winning score is greater than the halftime score, then we're in the second half

If the winning score is the halftime score, check the previous status.
If the previous status was halftime or second half, then we're at second half. Otherwise, it's halftime!

**Comment by Beamanator** [comment]
Only create status notification for halftime.

**Comment by Beamanator** [comment]
Code will go in GameDisplayFragment.showHalftimeNotification
